name: mynotes
description: "My notes."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  share_plus: ^11.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
