// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0dUed66MfASX7183foQbMUbo1Omg0_zg',
    appId: '1:127850045174:android:6aa218e2b13f0893d156d7',
    messagingSenderId: '127850045174',
    projectId: 'my-notes-utku',
    storageBucket: 'my-notes-utku.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3u47pPbRBCP12Uh67SfxngZaZ7NFgQwQ',
    appId: '1:127850045174:ios:584c62d60f414e77d156d7',
    messagingSenderId: '127850045174',
    projectId: 'my-notes-utku',
    storageBucket: 'my-notes-utku.firebasestorage.app',
    iosBundleId: 'com.utku.mynotes',
  );
}
